spring.application.name=hookrelay
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/hookrelay
spring.datasource.username=hookrelay
spring.datasource.password=hookrelay


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


springdoc.swagger-ui.path=docs

# jwt
spring.jwt.secret=67676rvytr2grygr782yr3824y384y83y4vryer7y473y4vy48723y4v234ggy3o42343y4723y423y4837y437y43y4723y4p
spring.jwt.expiration=86400000

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.devtools.restart.enabled=true

# docker run -d -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=tododb --name mysqldb -p 3301:3306 mysql:8.0